Repository croct-tech/plug-google-analytics-js, pull requests merged in 2020-06, with the labels that each got.

#14 Fix event option not passed to plugin
  src/index.ts
  src/plugin.ts
  test/index.test.ts
  test/plugin.test.ts
Labels: bug

#15 Add support for whitelisting specific custom events
  src/index.ts
  src/plugin.ts
  test/index.test.ts
  test/plugin.test.ts
Labels: feature

#16 Update readme example
  README.md
Labels: documentation

#17 Remove custom variable option from example to avoid confusion
  README.md
Labels: documentation
