Repository croct-tech/plug-google-analytics-js, pull requests merged in 2020-05, with the labels that each got.

#5 Remove app ID from example in readme
  README.md
Labels: documentation

#6 Bump plug version to 0.2.0-beta.9
  package-lock.json
  package.json
Labels: maintenance

#7 Update Github token
  .github/workflows/release-drafter.yaml
Labels: maintenance

#8 Fix options typing
  src/index.ts
Labels: bug

#9 Fix Jest configuration to transpile ES2015 modules
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  test/index.test.ts
Labels: maintenance

#10 Import Typescript runtime
  package-lock.json
  package.json
  tsconfig.json
Labels: maintenance

#13 Bump croct/plug to the latest version
  package-lock.json
  package.json
Labels: maintenance
